import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { Login } from "@/components/login/Login";
import { useWeb3Modal } from "@web3modal/wagmi/react";
import { useAccount, useDisconnect } from "wagmi";
import { ConnectBtn } from "@/components/sub/button/ConnectBtn";
import { Loader } from "@/components/Loader/Loader";

export default function CloudBoost() {
	const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
		useState(false);
	const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);

	const { open, close } = useWeb3Modal()
	const { address } = useAccount()
	const { disconnect } = useDisconnect()


	const closeAll = () => {
		setIsNetworkSwitchHighlighted(false);
		setIsConnectHighlighted(false);
	};
	console.log("account", address);

	return (
		<>
			<Head>
				<title>Login with wallet</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			

			<main className={styles.main}>
				{
					(address) ? 
					<div className="text-3xl font-semibold text-white">Cloud Boost</div>
:null
				}
				<div className={styles.wrapper}>
					<div className="max-w-4xl mx-auto -mt-20 w-[30rem] relative overflow-hidden z-10
				 bg-gray-800 p-8 rounded-lg shadow-md 
				 before:w-24 before:h-24 before:absolute before:bg-purple-600 before:rounded-full 
				 before:-z-10 before:blur-2xl after:w-32 after:h-32 after:absolute after:bg-sky-400
				  after:rounded-full after:-z-10 after:blur-xl after:top-24 after:-right-12">
						{
							(!address) ?
								<>
									<h2 className="text-2xl font-bold text-white mb-6">Connect your wallet</h2>
									<div className="flex justify-center">
										<div className="" onClick={() => open()}>
											<ConnectBtn text={"Connect"} />
										</div>
									</div>
									</>
								:
								<>
									<Loader />
								</>
						}
					</div>
				</div>
			</main>
		</>
	);
}
