import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useCallback, useEffect, useState } from "react";
import { Login } from "@/components/login/Login";
import { useWeb3Modal } from "@web3modal/wagmi/react";
import { useAccount, useDisconnect } from "wagmi";
import { ConnectBtn } from "@/components/sub/button/ConnectBtn";
import { Loader } from "@/components/Loader/Loader";
import axios from "axios";

export default function CloudBoost() {
	const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
    useState(false);
  const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);
  const [referred, setReferred] = useState(""); // New state to hold referredBy value

  const { open, close } = useWeb3Modal();
  const { address } = useAccount();
  const { disconnect } = useDisconnect();

  const handleConnect = useCallback(async () => {
    try {
      const user = {
        user_id: address,
        referralCode: Math.random().toString(36).substring(2, 8),
        referredBy: referred,
      };

      const response = await axios.post('https://web3-0ujz.onrender.com/api/v1/auth/registration', user, {
        headers: {
          'Content-Type': 'application/json',
        },
      });

      console.log(response.data);
    } catch (error) {
      console.error('Registration failed', error);
      console.log('Full error object:', error);
    }
  }, [address, referred]);

  useEffect(() => {
    if (address) {
      console.log("------>account", address);
      handleConnect();
    }
  }, [address, handleConnect]);

  const closeAll = () => {
    setIsNetworkSwitchHighlighted(false);
    setIsConnectHighlighted(false);
  };


	

	return (
		<>
			<Head>
				<title>Login with wallet</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			

			<main className={styles.main}>
				{
					(address) ? 
					<div className="text-3xl font-semibold text-white">Cloud Boost</div>
:null
				}
				<div className={styles.wrapper}>
					<div className="max-w-4xl mx-auto -mt-20 w-[30rem] relative overflow-hidden z-10
				 bg-gray-800 p-8 rounded-lg shadow-md 
				 before:w-24 before:h-24 before:absolute before:bg-purple-600 before:rounded-full 
				 before:-z-10 before:blur-2xl after:w-32 after:h-32 after:absolute after:bg-sky-400
				  after:rounded-full after:-z-10 after:blur-xl after:top-24 after:-right-12">
						{
							(!address) ?
							<div className="flex justify-center flex-col">
							  <h2 className="text-2xl font-bold text-white mb-6 text-center">Connect your wallet</h2>
                  <div className="flex flex-col mx-auto gap-5 justify-center">
                    <h2>Enter referral code</h2>
                    <input
                      type="text"
                      placeholder="Referred by (optional)"
                      value={referred}
                      onChange={(e) => setReferred(e.target.value)}
                      className="block w-full px-6 py-3 text-black bg-white border border-gray-200 rounded-full appearance-none placeholder:text-gray-400 focus:border-blue-500 focus:outline-none focus:ring-blue-500 sm:text-sm max-w-[220px]"
                    />

                    <div className="ml-3 py-2" onClick={() => open()}>
                      <ConnectBtn  text={"Login with your wallet"} />
                    </div>
                  </div>
						  </div>
								:
								<>
									<Loader />
								</>
						}
					</div>
				</div>
{/* 
        n
    <DePayButtons.DePayButton
      integration={ props.integration }
      payload={ props.payload }
      blockchains={ props.blockchains }
    /> */}
			</main>
		</>
	);
}
