import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { Login } from "@/components/login/Login";
import { useWeb3Modal } from "@web3modal/wagmi/react";
import { useAccount, useDisconnect } from "wagmi";
import { ConnectBtn } from "@/components/sub/button/ConnectBtn";
import { Loader } from "@/components/Loader/Loader";
import { Wallet } from "@/components/wallet/Wallet";

export default function Home() {
	const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
		useState(false);
	const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);

    const { open, close } = useWeb3Modal()
    const {address} = useAccount()
    const { disconnect } = useDisconnect()

	
	const closeAll = () => {
		setIsNetworkSwitchHighlighted(false);
		setIsConnectHighlighted(false);
	};
	console.log("account",address);
	
	return (
		<>
			<Head>
				<title>Login with wallet</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<div
					className={styles.backdrop}
					style={{
						opacity:
							isConnectHighlighted || isNetworkSwitchHighlighted
								? 1
								: 0,
					}}
				/>
				<div className={styles.header}>
					<div className="flex gap-3 items-center">
					<img className="h-16 w-12" src="https://uiverse.io/build/_assets/sad-astronaut-2GA54L3F.png" alt="" />
					<span className="font-semibold text-lg">Web 3 Connect</span>
					</div>
					<div className={styles.buttons}>
						{
							(!address)?<div
							onClick={closeAll}
							className={`${styles.highlight} ${
								isNetworkSwitchHighlighted
									? styles.highlightSelected
									: ``
							}`}
						>
							<w3m-network-button />
						</div>
						:
						null
						}
						
						<div
							onClick={closeAll}
							className={`${styles.highlight} ${
								isConnectHighlighted
									? styles.highlightSelected
									: ``
							}`}
						>
							<w3m-button />
						</div>
						{
							(address)?
							<div className="" onClick={() => disconnect()}>
								<ConnectBtn text={"Disonnect"}/> 
							</div>: null
						}
					
					</div>
				</div>
			</header>
			
			<main className={styles.main}>
				{
					(address)?
					<div className="fixed top-28 right-10 flex justify-end">
					<Wallet/>
				</div>: null
				}
				
				<div className={styles.wrapper}>
				<div
  className="max-w-md mx-auto relative overflow-hidden z-10 bg-gray-800 p-8 rounded-lg shadow-md before:w-24 before:h-24 before:absolute before:bg-purple-600 before:rounded-full before:-z-10 before:blur-2xl after:w-32 after:h-32 after:absolute after:bg-sky-400 after:rounded-full after:-z-10 after:blur-xl after:top-24 after:-right-12"
>
	{
		(!address)?
		<>
		<h2 className="text-2xl font-bold text-white mb-6">Connect your wallet</h2>

<div className="flex justify-center">
 
	<div className="" onClick={() => open()}>
		<ConnectBtn text={"Connect"}/>
	</div>

 </div></>

		:
		<>
		<Loader/>
		</>
	}
  
 
</div>
				</div>
			</main>
		</>
	);
}
